import nltk
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
import numpy as np

nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)

# ─── BLEU Score (Captioning) ────────────────────────────────────────────
def compute_bleu(reference: str, hypothesis: str) -> float:
    """
    Compares generated caption against ground truth caption.
    reference  = ground truth caption (from dataset)
    hypothesis = caption generated by the model
    Returns score between 0 and 1. Higher is better.
    """
    ref_tokens = nltk.word_tokenize(reference.lower())
    hyp_tokens = nltk.word_tokenize(hypothesis.lower())
    smoothie = SmoothingFunction().method4
    score = sentence_bleu([ref_tokens], hyp_tokens, smoothing_function=smoothie)
    return round(score, 4)


# ─── IoU Score (Grounding) ──────────────────────────────────────────────
def compute_iou(box_pred: list, box_gt: list) -> float:
    """
    Compares predicted bounding box against ground truth box.
    box_pred = [x1, y1, x2, y2] from Grounding DINO
    box_gt   = [x1, y1, x2, y2] from dataset annotations
    Returns score between 0 and 1. Higher is better.
    """
    px1, py1, px2, py2 = box_pred
    gx1, gy1, gx2, gy2 = box_gt

    inter_x1 = max(px1, gx1)
    inter_y1 = max(py1, gy1)
    inter_x2 = min(px2, gx2)
    inter_y2 = min(py2, gy2)

    inter_area = max(0, inter_x2 - inter_x1) * max(0, inter_y2 - inter_y1)
    pred_area = (px2 - px1) * (py2 - py1)
    gt_area = (gx2 - gx1) * (gy2 - gy1)
    union_area = pred_area + gt_area - inter_area

    if union_area == 0:
        return 0.0

    return round(inter_area / union_area, 4)


# ─── VQA Accuracy ──────────────────────────────────────────────────────
def compute_vqa_accuracy(predicted: str, ground_truth: str) -> float:
    """
    Simple exact match accuracy for VQA.
    predicted    = model's answer
    ground_truth = correct answer from dataset
    Returns 1.0 if correct, 0.0 if wrong.
    """
    return 1.0 if predicted.strip().lower() == ground_truth.strip().lower() else 0.0


# ─── Batch Evaluation ──────────────────────────────────────────────────
def evaluate_captions(references: list, hypotheses: list) -> dict:
    """
    Runs BLEU on a list of caption pairs.
    Both lists must be same length.
    Returns average BLEU score across all pairs.
    """
    scores = [compute_bleu(r, h) for r, h in zip(references, hypotheses)]
    return {
        "individual_scores": scores,
        "average_bleu": round(np.mean(scores), 4)
    }


def evaluate_boxes(pred_boxes: list, gt_boxes: list) -> dict:
    """
    Runs IoU on a list of box pairs.
    Returns average IoU score across all pairs.
    """
    scores = [compute_iou(p, g) for p, g in zip(pred_boxes, gt_boxes)]
    return {
        "individual_scores": scores,
        "average_iou": round(np.mean(scores), 4)
    }


def evaluate_vqa(predictions: list, ground_truths: list) -> dict:
    """
    Runs VQA accuracy on a list of answer pairs.
    Returns accuracy percentage.
    """
    scores = [compute_vqa_accuracy(p, g) for p, g in zip(predictions, ground_truths)]
    return {
        "individual_scores": scores,
        "accuracy": round(np.mean(scores) * 100, 2)
    }
